### ISSUE TITLE
헤더 컴포넌트 렌더링 관련 이슈

### ISSUE THREAD

**Issue by dorimu0** [yju-FukuFuku/FukuFuku_Frontend_Refactoring-repo#44]
- [ ] 헤더 리렌더링 ( 버벅거림 )
- [ ] /setting 페이지에서 보면 이해가 빠를거에요

**Comment by dorimu0** [comment]
@hetame1 고쳐주세요

**Comment by Z00One** [comment]
@dorimu0 
/mypage 페이지, /setting 페이지에서 렌더링이 너무 많이 일어납니다. 해당 페이지 렌더링 최적화 해주세요.
